" XDG Base Directory support
" by https://blog.joren.ga/tools/vim-xdg
if empty($MYVIMRC) | let $MYVIMRC = expand('<sfile>:p') | endif

if empty($XDG_CACHE_HOME)   | let $XDG_CACHE_HOME   = $HOME."/.cache"       | endif
if empty($XDG_CONFIG_HOME)  | let $XDG_CONFIG_HOME  = $HOME."/.config"      | endif
if empty($XDG_DATA_HOME)    | let $XDG_DATA_HOME    = $HOME."/.local/share" | endif

set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after

let g:netrw_home = $XDG_DATA_HOME."/vim"
call mkdir($XDG_DATA_HOME."/vim/spell", 'p', 0700)
set viewdir=$XDG_DATA_HOME/vim/view | call mkdir(&viewdir, 'p', 0700)

set backupdir=$XDG_CACHE_HOME/vim/backup    | call mkdir(&backupdir, 'p', 0700)
set directory=$XDG_CACHE_HOME/vim/swap      | call mkdir(&directory, 'p', 0700)
set undodir=$XDG_CACHE_HOME/vim/undo        | call mkdir(&undodir,   'p', 0700)
set viminfofile=$XDG_CACHE_HOME/vim/viminfo

" basics
set nocompatible
set number
set relativenumber
set cursorline
syntax on

filetype plugin on
filetype indent on

" cheap built-in fuzuy finder
" by https://github.com/changemewtf/no_plugins/blob/master/no_plugins.vim
set path+=**
set wildmenu

" Tabstops
set tabstop=4
set shiftwidth=4
set expandtab

" indent
set autoindent

" easier reachable ESC key
" mapped to both jk and kj so the order doesn't matter (and I can press them
" at the same time)
inoremap jk <Esc>
inoremap kj <Esc>

" always show the statusline (for airline)
set laststatus=2
" mode is shown by airline
set noshowmode

" plugins (vim-plug)
call plug#begin($XDG_DATA_HOME.'/vim/plugged')

Plug 'tpope/vim-sensible'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'altercation/vim-colors-solarized'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'mattn/emmet-vim'
Plug 'junegunn/vim-emoji'
Plug 'pearofducks/ansible-vim'

call plug#end()

" colorscheme
set background=dark
let g:solarized_termtrans=1
colorscheme solarized

" airline
let g:airline_powerline_fonts=1
let g:airline_skip_empty_sections=1

" emmet
" enabled only in html and css files, and only in insert mode
let g:user_emmet_install_global = 0
autocmd FileType html,css EmmetInstall
"let g:user_emmet_mode='i'

" vim-emoji (emoji autocompletion via <C-X><C-U>) in markdown files
augroup emoji_complete
    autocmd!
    autocmd FileType markdown setlocal completefunc=emoji#complete
    autocmd FileType markdown command -buffer Emojify s/:\([^:]\+\):/\=emoji#for(submatch(1), submatch(0))/g
augroup END

" mail editing from mutt
augroup filetypedetect
    " Mail
    autocmd BufRead,BufNewFile *mutt-*      setfiletype mail
augroup END
